name = "jvelo-at"
main = "src/index.tsx"
compatibility_date = "2025-01-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAACsq9y4begav6jOv"

[observability]
enabled = true
