import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { marked } from 'marked';
import { fileURLToPath } from 'url';
import type { PageData, PageType, ResumeData } from '../src/types';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const contentDir = path.join(__dirname, '..', 'content');
const outputFile = path.join(__dirname, '..', 'src', 'content-bundle.ts');

function processMarkdownFile(filePath: string, slug: string): PageData {
  const fileContents = fs.readFileSync(filePath, 'utf8');
  const { data, content } = matter(fileContents);

  return {
    slug,
    type: (data.type as PageType) || 'page',
    title: data.title || '',
    subtitle: data.subtitle || undefined,
    description: data.description || undefined,
    image: data.image || undefined,
    badge: data.badge || undefined,
    technologies: data.technologies || undefined,
    years: data.years || undefined,
    license: data.license || undefined,
    source: data.source || undefined,
    content,
    html: marked(content) as string,
  };
}

const inline = (s: string) => marked.parseInline(s) as string;

function processResume(filePath: string): ResumeData {
  // gray-matter bundles a YAML parser; reading the file as front matter avoids another dependency.
  const data = matter(`---\n${fs.readFileSync(filePath, 'utf8')}\n---`).data as ResumeData;
  return {
    ...data,
    summary: inline(data.summary),
    experience: data.experience.map((e) => ({
      dates: e.dates,
      roles: e.roles.map((r) => ({
        ...r,
        summary: r.summary && inline(r.summary),
        bullets: r.bullets?.map(inline),
      })),
    })),
    projects: data.projects.map((p) => ({ ...p, summary: inline(p.summary) })),
  };
}

function bundleContent() {
  console.log('Bundling content...');

  const bundle: { home: PageData; pages: Record<string, PageData>; resume: ResumeData } = {
    home: processMarkdownFile(path.join(contentDir, 'home', 'index.md'), 'home'),
    pages: {},
    resume: processResume(path.join(__dirname, '..', 'resume', 'resume.yaml')),
  };

  const pagesDir = path.join(contentDir, 'pages');
  const pageFiles = fs.readdirSync(pagesDir);

  for (const file of pageFiles) {
    if (file.endsWith('.md')) {
      const slug = file.replace('.md', '');
      const filePath = path.join(pagesDir, file);
      bundle.pages[slug] = processMarkdownFile(filePath, slug);
    }
  }

  const output = `// Auto-generated by scripts/bundle-content.ts
// Do not edit this file directly

import type { PageData, ResumeData } from './types';

export const contentBundle: {
  home: PageData;
  pages: Record<string, PageData>;
  resume: ResumeData;
} = ${JSON.stringify(bundle, null, 2)};
`;

  fs.writeFileSync(outputFile, output, 'utf8');
  console.log(`✅ Content bundled to ${outputFile}`);
  console.log(`   - Home page`);
  console.log(`   - ${Object.keys(bundle.pages).length} pages: ${Object.keys(bundle.pages).join(', ')}`);
}

bundleContent();
