import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { marked } from 'marked';
import { fileURLToPath } from 'url';
import type { PageData, PageType } from '../src/types';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const contentDir = path.join(__dirname, '..', 'content');
const outputFile = path.join(__dirname, '..', 'src', 'content-bundle.ts');

function processMarkdownFile(filePath: string, slug: string): PageData {
  const fileContents = fs.readFileSync(filePath, 'utf8');
  const { data, content } = matter(fileContents);

  return {
    slug,
    type: (data.type as PageType) || 'page',
    title: data.title || '',
    subtitle: data.subtitle || undefined,
    description: data.description || undefined,
    image: data.image || undefined,
    badge: data.badge || undefined,
    technologies: data.technologies || undefined,
    years: data.years || undefined,
    license: data.license || undefined,
    source: data.source || undefined,
    content,
    html: marked(content) as string,
  };
}

function bundleContent() {
  console.log('Bundling content...');

  const bundle: { home: PageData; pages: Record<string, PageData> } = {
    home: processMarkdownFile(path.join(contentDir, 'home', 'index.md'), 'home'),
    pages: {},
  };

  const pagesDir = path.join(contentDir, 'pages');
  const pageFiles = fs.readdirSync(pagesDir);

  for (const file of pageFiles) {
    if (file.endsWith('.md')) {
      const slug = file.replace('.md', '');
      const filePath = path.join(pagesDir, file);
      bundle.pages[slug] = processMarkdownFile(filePath, slug);
    }
  }

  const output = `// Auto-generated by scripts/bundle-content.ts
// Do not edit this file directly

import type { PageData } from './types';

export const contentBundle: {
  home: PageData;
  pages: Record<string, PageData>;
} = ${JSON.stringify(bundle, null, 2)};
`;

  fs.writeFileSync(outputFile, output, 'utf8');
  console.log(`✅ Content bundled to ${outputFile}`);
  console.log(`   - Home page`);
  console.log(`   - ${Object.keys(bundle.pages).length} pages: ${Object.keys(bundle.pages).join(', ')}`);
}

bundleContent();
