on: [push, pull_request]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: git fetch --prune --unshallow --tags
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - uses: actions/cache@v4
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn lint
