name: Twitter things

on:
  schedule:
    - cron: "37 13 * * *"

jobs:
  get-likes:
    runs-on: ubuntu-latest
    name: Save latest likes in DB
    environment: production
    env:
      DB_DATABASE: jvelo_at
      DB_HOST: mysql.jvelo.at
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_USERNAME: jvelo

    defaults:
      run:
        working-directory: ./actions/twitter
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn

      - name: Run script
        run: |
          ./node_modules/.bin/ts-node get-likes.ts
